version: '3'
services:
  mongodb:
    image: mongo
    container_name: countless-dev-mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    networks:
       countless-dev:
        ipv4_address: ${IP_MONGODB}
      
  mongo-express:
    image: mongo-express
    container_name: countless-dev-mongo-express    
    ports:
      - "8080:8081"
    restart: unless-stopped       
    networks:
      - countless-dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_ADMIN_SERVER}
      
  backend: 
    image: countless-backend:latest
    container_name: countless-dev-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - countless-dev
    environment:
      GIT_REPOSITORY: ${GIT_REPOSITORY}
      MONGO_ADMIN_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}
      CRYPT_SECRET: ${CRYPT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}



networks:
  countless-dev:
    name: countless-dev
    ipam:
      driver: default
      config:
        - subnet: ${MASK_MONGODB}