ktor:
    application:
        modules:
            - org.akrck02.ApplicationKt.module
    deployment:
        port: 8000
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
